### ISSUE TITLE
All "See Also" links to Github pages are missing the dot before the extension

### ISSUE THREAD

**Issue by per1234** [arduino/reference-en#19]
For example the [noTone](https://github.com/arduino/reference-en/blob/master/Language/Functions/Advanced%20IO/noTone.adoc) page's **See Also** link points to:
https://github.com/arduino/reference-en/blob/master/Language/Functions/Advanced%20IO/toneadoc
Instead the link should be:
https://github.com/arduino/reference-en/blob/master/Language/Functions/Advanced%20IO/tone.adoc

**Comment by per1234** [comment]
I think the solution is either:
- Change `:ext-relative: adoc` to `:ext-relative: .adoc`
- Change `* #LANGUAGE# link:tone{ext-relative}[tone()]` to `* #LANGUAGE# link:tone.{ext-relative}[tone()]`

I'm happy to make the changes and submit a pull request but I don't know which change will work correctly with how the extension is changed to .html during compilation.

**Comment by 00alis** [comment]
@mastrolinux could you gibe @per1234 some guidance on how to fix this?

**Comment by smellai** [comment]
I think this is ok now? 
https://cdn.arduino.cc/reference/en/language/functions/advanced-io/notone/
@per1234 can you confirm?

**Comment by per1234** [comment]
Looks good, thanks!
