### ISSUE TITLE
revert to https://www.arduino.cc/en/Reference/AttachInterrupt/

### ISSUE THREAD

**Issue by RTClib-user** [arduino/reference-en#193]
several recent revisions including the recommended syntax have been dropped

attachInterrupt(digitalPinToInterrupt(pin), ISR, mode); | (recommended)
-- | --

**Comment by RTClib-user** [comment]
http://forum.arduino.cc/index.php?topic=510227.msg3477948#msg3477948

**Comment by smellai** [comment]
it should be fixed with https://github.com/arduino/reference-en/pull/196, thanks for you report!
