### ISSUE TITLE
 expected '}' before 'else' Return Arduino [C]

### ISSUE THREAD

**Issue by scoolboy** [arduino/reference-en#225]
Language/Structure/Control Structure/return.adoc

[source,arduino]
----
 int checkSensor(){
    if (analogRead(0) > 400) {
        return 1;
    } // <-- Added } closing return1; (if function).
    else{
        return 0;
    }
}
----
Syntax error,  error: expected '}' before 'else'

**Comment by smellai** [comment]
Already fixed https://github.com/arduino/reference-en/pull/200/files
