### ISSUE TITLE
I want to make Korean translation of arduino reference

### ISSUE THREAD

**Issue by sebuls** [arduino/reference-en#227]
I want translate https://www.arduino.cc/reference/en/ into Korean.

How can make
https://www.arduino.cc/reference/ko/ and copy 
https://www.arduino.cc/reference/en into 
https://www.arduino.cc/reference/ko
and translate ?

P.S.
Which is better ko or kr ?
I think ko is better than kr.
Reference : https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by Fede85** [comment]
repo created
https://github.com/arduino/reference-ko

**Comment by smellai** [comment]
Thank you so much @sebuls ! Just give us some more days to have the 'en' repo more stable and I'll clone it to the 'ko' one.

**Comment by smellai** [comment]
Hi @sebuls , I uploaded the content on -ko repo
