### ISSUE TITLE
Old reference links with / as last char do not redirect

### ISSUE THREAD

**Issue by smellai** [arduino/reference-en#236]
https://www.arduino.cc/en/Reference/max 

https://www.arduino.cc/en/Reference/max/

**Comment by smellai** [comment]
This page is still available https://www.arduino.cc/en/Reference/KeyboardPress

**Comment by endorama** [comment]
Added redirects:
- https://www.arduino.cc/en/Reference/KeyboardPress => https://www.arduino.cc/reference/en/language/functions/usb/keyboard/keyboardpress/
- https://www.arduino.cc/en/Reference/max/ => https://www.arduino.cc/reference/en/language/functions/math/max/

(expect cache to last few hours)

**Comment by endorama** [comment]
Redirects are working, closing.

**Comment by per1234** [comment]
@endorama the https://www.arduino.cc/en/Reference/max/ URL was only an example of the problem. The issue of old reference URLs not redirecting if they have a trailing slash occurs for **all** old reference URLs (except for https://www.arduino.cc/en/Reference/max/ now).

For example:
https://www.arduino.cc/en/Reference/min/
still doesn't redirect even though:
https://www.arduino.cc/en/Reference/min
does redirect.

**Comment by endorama** [comment]
@per1234 please have a look at it now, I should have been able to provide a fix
