### ISSUE TITLE
Strange first character at a file.

### ISSUE THREAD

**Issue by sebuls** [arduino/reference-en#270]
First character at
https://github.com/arduino/reference-en/edit/master/Language/Variables/Data%20Types/String/Operators/append.adoc
is strange.

What is it ? BOM ?

**Comment by SeppPenner** [comment]
Looks better now: https://github.com/SeppPenner/reference-en/blob/ab9210139534791e9a06a4de7f4c62941ad5d428/Language/Variables/Data%20Types/String/Operators/append.adoc

PR is there: https://github.com/arduino/reference-en/pull/384

**Comment by SeppPenner** [comment]
Is fixed in the German repository ;) https://github.com/arduino/reference-de/pull/21

However, someone should fix this here using my pull request.

**Comment by SeppPenner** [comment]
PR is there for spanish repo, too. https://github.com/arduino/reference-es/pull/112

**Comment by SeppPenner** [comment]
Fixed in French: https://github.com/arduino/reference-fr/pull/13

**Comment by SeppPenner** [comment]
Fixed in italian repo: https://github.com/arduino/reference-it/pull/112

**Comment by SeppPenner** [comment]
I think, this issue can be closed. Seperate PRs are already present in any other affected language repository.

**Comment by SeppPenner** [comment]
@mastrolinux Can you close this, please. Thank you ;)
