### ISSUE TITLE
Missing pages: Mouse and Keyboard

### ISSUE THREAD

**Issue by 00alis** [arduino/reference-en#28]
This page http://www.arduino.cc/en/Reference/MouseKeyboard is missing its adoc documents (one per Mouse and one per Keyboard), would it be possible to create it as well?

Thanks!

**Comment by sh-aks** [comment]
@00alis: Files Added in the branch Mouse_Keyboard_Fix
Will raise a pull request, after the discussion.

Did not understand where to add the Caution which is common for both the library.
Should we put on both the pages?
![image](https://cloud.githubusercontent.com/assets/5464880/14653285/f23e03c0-0695-11e6-983a-e39986cdc57b.png)

**Comment by 00alis** [comment]
Yes please I think it is best to add it to both pages, thank you!

**Comment by sh-aks** [comment]
@00alis : Added Notes and Warning Section.
Closing the issue and Making a pull request.

**Comment by sh-aks** [comment]
Pending Pull request.
