### ISSUE TITLE
Output from example code on Serial.print() is messy

### ISSUE THREAD

**Issue by shane-lawson** [arduino/reference-en#317]
The sample code at the page https://github.com/arduino/reference-en/blob/master/Language/Functions/Communication/Serial/print.adoc yields 
![image](https://user-images.githubusercontent.com/25392583/37228299-0c8e15ec-23d8-11e8-9c13-ca1c26bbb034.png) 
in the Arduino serial monitor. This is messy and difficult to tell what's going on if you're not familiar with the serial output.

**Comment by SimonePDA** [comment]
Fixed with pull request  #345
