### ISSUE TITLE
link to pgmspace.h broken

### ISSUE THREAD

**Issue by s-light** [arduino/reference-en#382]
in [/Language/Variables/Utilities/PROGMEM.adoc](https://github.com/arduino/reference-en/blob/master/Language/Variables/Utilities/PROGMEM.adoc) the URLs pointing to the [pgmspace.h website](http://www.nongnu.org/avr-libc/user-manual/group__avr__pgmspace.html) are broken.
they render with an `<em>` in them - but there should be some `__` in them.
check source at
[PROGMEM.adoc#L24](https://github.com/arduino/reference-en/blame/master/Language/Variables/Utilities/PROGMEM.adoc#L24)
[PROGMEM.adoc#L47](https://github.com/arduino/reference-en/blame/master/Language/Variables/Utilities/PROGMEM.adoc#L47)
and result at
[PROGMEM.adoc#description](https://github.com/arduino/reference-en/blob/master/Language/Variables/Utilities/PROGMEM.adoc#description)
results in 
`http://www.nongnu.org/avr-libc/user-manual/group<em>avr</em>pgmspace.html`
but should be
`http://www.nongnu.org/avr-libc/user-manual/group__avr__pgmspace.html`

**Comment by per1234** [comment]
There's an existing PR to fix this:
https://github.com/arduino/reference-en/pull/360

**Comment by s-light** [comment]
sorry i didn't found it.
should i /we close this duplicate?

**Comment by SeppPenner** [comment]
Can be closed @robsoncouto ;) You already fixed this with https://github.com/arduino/reference-en/pull/360 or https://github.com/arduino/reference-en/commit/c96a93a5fb97c69767ff5a520d6fa22621c5e28f
