### ISSUE TITLE
Align Licences

### ISSUE THREAD

**Issue by smellai** [arduino/reference-en#39]
This repo has CC 3.0 https://github.com/arduino/reference-en/blob/master/LICENSE.md
while glossary has 4.0 https://github.com/arduino/glossary-content

**Comment by mastrolinux** [comment]
that's OK I think. glossary is a newer repo and for reference we do not want to change license.

**Comment by smellai** [comment]
Also shown here:
![image](https://user-images.githubusercontent.com/1763268/26887833-6d32d700-4ba9-11e7-900c-97c3e3a34a20.png)

**Comment by smellai** [comment]
Ok! I'll change the text in the sidebar just for glossary, thanks
