### ISSUE TITLE
Show syntax instructions / template in Readme or somewhere else

### ISSUE THREAD

**Issue by smellai** [arduino/reference-en#41]
see https://github.com/arduino/reference-en/issues/24

**Comment by smellai** [comment]
https://cdn.arduino.cc/reference/en/asciidoc_sample/reference_terms/asciidoc_template-single_entity/

https://cdn.arduino.cc/reference/en/asciidoc_sample/reference_terms/asciidoc_template-parent_of_entities/

https://cdn.arduino.cc/reference/en/asciidoc_sample/asciidoc_dictionary/asciidoc_template-dictionary/

**Comment by 00alis** [comment]
I am not sure where they can be, it was useful for me to have them in the repo cause users could start from it to write new entries. If not too long let's add it to the readme?

**Comment by smellai** [comment]
Restored examples folders and added links in readme
