### ISSUE TITLE
Question: Can I get contributor access?

### ISSUE THREAD

**Issue by SeppPenner** [arduino/reference-en#420]
Hi @smellai and @mastrolinux.

As you might know, I'm the one who mainly translates the German repository.
If you don't mind, I would like to support you on the English repository (here), too.

If you give me contributer access, I can check the PRs here, validate and merge them if you don't have time.

Would be a nice thing I suppose :) 👍

**Comment by mastrolinux** [comment]
@endorama please proceed

**Comment by SeppPenner** [comment]
Hi @mastrolinux  I could help you as well. Together with @robsoncouto: https://github.com/arduino/reference-en/issues/448

**Comment by robsoncouto** [comment]
HI @SeppPenner, thanks for your interest. I don't really think it is really necessary though.

**Comment by SeppPenner** [comment]
Okay.
