### ISSUE TITLE
detachInterrupt.adoc has either an error in the syntax part or in the parameters part

### ISSUE THREAD

**Issue by SeppPenner** [arduino/reference-en#425]
detachInterrupt.adoc has either an error in the syntax part or in the parameters part:

![grafik](https://user-images.githubusercontent.com/9639361/45474745-d8516800-b73a-11e8-9405-03fdc8aefbaf.png)

![grafik](https://user-images.githubusercontent.com/9639361/45474753-ddaeb280-b73a-11e8-9e48-dbba99e8444b.png)

There is no parameter called `interrupt` in the Syntax area??

https://github.com/arduino/reference-en/blob/master/Language/Functions/External%20Interrupts/detachInterrupt.adoc

What's correct here?

**Comment by robsoncouto** [comment]
This has been fixed in 257dbf5e5cf96d537abe13d276c451fe97a89e79
