### ISSUE TITLE
const.adoc does not reference to #define properly

### ISSUE THREAD

**Issue by SeppPenner** [arduino/reference-en#434]
https://github.com/arduino/reference-en/edit/master/Language/Variables/Variable%20Scope%20&%20Qualifiers/const.adoc

#define is only referenced correctly once.

**Comment by robsoncouto** [comment]
#434 was not accepted because there were enough mentions to the #define page already

**Comment by SeppPenner** [comment]
@robsoncouto In my opinion it would make sense to reference all occurences of these. But I will open a discussion in the issues.

**Comment by SeppPenner** [comment]
I have created an issue for a general discussion on this. In my opinion it would make sense to link every occurence of functions or constants. https://github.com/arduino/reference-en/issues/462
