### ISSUE TITLE
Unclear whether you can read pins set to OUTPUT mode

### ISSUE THREAD

**Issue by RobLewis** [arduino/reference-en#469]
Most microcontrollers allow reading the state of pins set to OUTPUT mode, but it isn't explicitly stated in the documentation whether this is supported.

**Comment by per1234** [comment]
My feeling is that this isn't a topic that needs to be documented in the Language Reference. Best practices is to store the output pin state in a variable. Documenting the ability to read from a pin set to OUTPUT will only lead people to write less efficient code that may not be portable to all architectures.

If people do want to do this, there are quite a few topics on the Arduino Forum about it they will find with a search.
