### ISSUE TITLE
Serial.write(buf,len) missing description of len parameter

### ISSUE THREAD

**Issue by sterretje** [arduino/reference-en#473]
There is no description of the 'len' parameter
> Syntax
Serial.write(val)
Serial.write(str)
**Serial.write(buf, len)**
>Arduino Mega also supports:
Serial1, Serial2, Serial3 (in place of Serial)
>
>Parameters
val: a value to send as a single byte
str: a string to send as a series of bytes
buf: an array to send as a series of bytes
>
>Returns
size_t
write() will return the number of bytes written, though reading that number is optional

**Comment by robsoncouto** [comment]
Yes. That is correct.
The Parameter section  is missing:
> len: the length of the array

Thanks for pointing it out :)

**Comment by sterretje** [comment]
> len: the length of the array

But that's not quite correct; you can have a 100 byte array but only want to send 10 bytes.

**Comment by robsoncouto** [comment]
> But that's not quite correct; you can have a 100 byte array but only want to send 10 bytes.

Oops, that is right. My bad.

How about the following?

> len: the number of bytes to be sent from the array

**Comment by sterretje** [comment]
I think beginners can live with that ;)

**Comment by robsoncouto** [comment]
Alright then. 
Thanks again :)
