### ISSUE TITLE
Outdated version of the Language Reference homepage still available online

### ISSUE THREAD

**Issue by per1234** [arduino/reference-en#474]
`https://www.arduino.cc/en/Reference/Extended` appears as the second result in a Google search for `arduino language reference` and the third for `arduino language`. This page redirects to `https://www.arduino.cc/en/Reference/HomePage?from=Reference.Extended`, which is an outdated version of https://www.arduino.cc/reference/en/.

I also found the outdated `https://www.arduino.cc/en/Reference/HomePage2`.

Is it possible to redirect `https://www.arduino.cc/en/Reference/Extended` and `https://www.arduino.cc/en/Reference/HomePage2` to https://www.arduino.cc/reference?

**Comment by endorama** [comment]
It seems that https://www.arduino.cc/en/Reference/Extended now correctly redirect to https://www.arduino.cc/reference/en/ already.

I added the redirect from https://www.arduino.cc/en/Reference/HomePage2 to https://www.arduino.cc/reference/en/

(expect cache to last for some hours)

**Comment by smellai** [comment]
Let's remove the old page from pmWiki as soon as the redirect works

**Comment by endorama** [comment]
Redirects are working, closing.

@smellai could you take care of removing the old page please?
