### ISSUE TITLE
Many old reference pages still don't redirect

### ISSUE THREAD

**Issue by per1234** [arduino/reference-en#481]
Many old reference pages still don't redirect (not necessarily a comprehensive list):
- `https://www.arduino.cc/en/Serial/IfSerial` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/serial/ifserial)
- `https://www.arduino.cc/en/Serial/Available` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/serial/available)
- `https://www.arduino.cc/en/Serial/AvailableForWrite` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/serial/availableforwrite)
- `https://www.arduino.cc/en/Serial/Begin` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/serial/begin)
- `https://www.arduino.cc/en/Serial/End` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/serial/end)
- `https://www.arduino.cc/en/Serial/Find` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/serial/find)
- `https://www.arduino.cc/en/Serial/FindUntil` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/serial/finduntil)
- `https://www.arduino.cc/en/Serial/Flush` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/serial/flush)
- `https://www.arduino.cc/en/Serial/ParseFloat` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/serial/parsefloat)
- `https://www.arduino.cc/en/Serial/ParseInt` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/serial/parseint)
- `https://www.arduino.cc/en/Serial/Peek` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/serial/peek)
- `https://www.arduino.cc/en/Serial/Print` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/serial/print)
- `https://www.arduino.cc/en/Serial/Println` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/serial/println)
- `https://www.arduino.cc/en/Serial/Read` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/serial/read)
- `https://www.arduino.cc/en/Serial/ReadBytes` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/serial/readbytes)
- `https://www.arduino.cc/en/Serial/ReadBytesUntil` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/serial/readbytesuntil)
- `https://www.arduino.cc/en/Serial/ReadString` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/serial/readstring)
- `https://www.arduino.cc/en/Serial/ReadStringUntil` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/serial/readstringuntil)
- `https://www.arduino.cc/en/Serial/SetTimeout` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/serial/settimeout)
- `https://www.arduino.cc/en/Serial/Write` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/serial/write)
- `https://www.arduino.cc/en/Reference/SerialEvent` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/serial/serialevent)
- `https://www.arduino.cc/en/Reference/StreamAvailable` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/stream/streamavailable)
- `https://www.arduino.cc/en/Reference/StreamRead` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/stream/streamread)
- `https://www.arduino.cc/en/Reference/StreamFlush` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/stream/streamflush)
- `https://www.arduino.cc/en/Reference/StreamFind` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/stream/streamfind)
- `https://www.arduino.cc/en/Reference/StreamFindUntil` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/stream/streamfinduntil)
- `https://www.arduino.cc/en/Reference/StreamPeek` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/stream/streampeek)
- `https://www.arduino.cc/en/Reference/StreamReadBytes` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/stream/streamreadbytes)
- `https://www.arduino.cc/en/Reference/StreamReadBytesUntil` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/stream/streamreadbytesuntil)
- `https://www.arduino.cc/en/Reference/StreamReadString` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/stream/streamreadstring)
- `https://www.arduino.cc/en/Reference/StreamReadStringUntil` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/stream/streamreadbytesuntil)
- `https://www.arduino.cc/en/Reference/StreamParseInt` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/stream/streamparseint)
- `https://www.arduino.cc/en/Reference/StreamParseFloat` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/stream/streamparsefloat)
- `https://www.arduino.cc/en/Reference/StreamSetTimeout` (should redirect to: https://www.arduino.cc/reference/en/language/functions/communication/stream/streamsettimeout)
- `https://www.arduino.cc/en/Reference/KeyboardBegin` (should redirect to: https://www.arduino.cc/reference/en/language/functions/usb/keyboard/keyboardbegin)
- `https://www.arduino.cc/en/Reference/KeyboardEnd` (should redirect to: https://www.arduino.cc/reference/en/language/functions/usb/keyboard/keyboardend)
- `https://www.arduino.cc/en/Reference/KeyboardPress` (should redirect to: https://www.arduino.cc/reference/en/language/functions/usb/keyboard/keyboardpress)
- `https://www.arduino.cc/en/Reference/KeyboardPrint` (should redirect to: https://www.arduino.cc/reference/en/language/functions/usb/keyboard/keyboardprint)
- `https://www.arduino.cc/en/Reference/KeyboardPrintln` (should redirect to: https://www.arduino.cc/reference/en/language/functions/usb/keyboard/keyboardprintln)
- `https://www.arduino.cc/en/Reference/KeyboardRelease` (should redirect to: https://www.arduino.cc/reference/en/language/functions/usb/keyboard/keyboardrelease)
- `https://www.arduino.cc/en/Reference/KeyboardReleaseAll` (should redirect to: https://www.arduino.cc/reference/en/language/functions/usb/keyboard/keyboardreleaseall)
- `https://www.arduino.cc/en/Reference/KeyboardWrite` (should redirect to: https://www.arduino.cc/reference/en/language/functions/usb/keyboard/keyboardwrite)
- `https://www.arduino.cc/en/Reference/MouseBegin` (should redirect to: https://www.arduino.cc/reference/en/language/functions/usb/mouse/mousebegin)
- `https://www.arduino.cc/en/Reference/MouseClick` (should redirect to: https://www.arduino.cc/reference/en/language/functions/usb/mouse/mouseclick)
- `https://www.arduino.cc/en/Reference/MouseEnd` (should redirect to: https://www.arduino.cc/reference/en/language/functions/usb/mouse/mouseend)
- `https://www.arduino.cc/en/Reference/MouseMove` (should redirect to: https://www.arduino.cc/reference/en/language/functions/usb/mouse/mousemove)
- `https://www.arduino.cc/en/Reference/MousePress` (should redirect to: https://www.arduino.cc/reference/en/language/functions/usb/mouse/mousepress
- `https://www.arduino.cc/en/Reference/MouseRelease` (should redirect to: https://www.arduino.cc/reference/en/language/functions/usb/mouse/mouserelease)
- `https://www.arduino.cc/en/Reference/MouseIsPressed` (should redirect to: https://www.arduino.cc/reference/en/language/functions/usb/mouse/mouseispressed)

I notice these are all from the library-style reference pages. In the case of Keyboard and Mouse, they really have no business being in the Language Reference any more since this code was broken out into libraries in Arduino IDE 1.6.6. On the other hand, having the Mouse and Keyboard content in the language reference makes it so we can actually get edits done on it so I won't complain too loudly.

Related issues:
- https://github.com/arduino/reference-en/issues/209
- https://github.com/arduino/reference-en/issues/236 (but note that none of the above end with `/` so this is not a duplicate.
- https://github.com/arduino/reference-en/issues/474

**Comment by endorama** [comment]
Added all required redirects!

Please note that arduino.cc/en/Reference/KeyboardPress has been reported in #236 also (not particularly interesting but webserver supports only 1 redirect per URL so be careful)

(expect cache to last few hours)

**Comment by endorama** [comment]
Redirects are working, closing.

**Comment by per1234** [comment]
@endorama I found a couple of issues so I'm re-opening this:
- https://www.arduino.cc/en/Reference/SerialEvent: doesn't redirect
- https://www.arduino.cc/en/Reference/StreamReadStringUntil: I provided the wrong redirect URL. It should have been https://www.arduino.cc/reference/en/language/functions/communication/stream/streamreadstringuntil/. Sorry about that!

Everything else is working perfectly. Thanks!

**Comment by endorama** [comment]
I fixed both. Please wait for cache to expire.
