### ISSUE TITLE
Incorrect redirects for old setup and loop pages

### ISSUE THREAD

**Issue by per1234** [arduino/reference-en#537]
https://www.arduino.cc/en/Reference/Setup
redirects to:
https://www.arduino.cc/reference/en/language/functions/main/setup/
but the correct URL is:
https://www.arduino.cc/reference/en/language/structure/sketch/setup/

---
https://www.arduino.cc/en/Reference/Loop
redirects to:
https://www.arduino.cc/reference/en/language/functions/main/loop/
but the correct URL is:
https://www.arduino.cc/reference/en/language/structure/sketch/loop/

---
This is not necessarily a comprehensive list. It's just the two instances I stumbled across on the "See also" section of this page:
https://www.arduino.cc/en/Tutorial/Sketch

There are previous issues related to redirects from the old reference URLs, but those have a difference cause than this one:

- https://github.com/arduino/reference-en/issues/236
- https://github.com/arduino/reference-en/issues/474
- https://github.com/arduino/reference-en/issues/481

**Comment by endorama** [comment]
updated redirects to `setup` and `loop`.

`pinMode` was also wrong, fixed.

(expect cache to last few hours)

**Comment by endorama** [comment]
Redirects are working, closing.
