### ISSUE TITLE
Add Note to mills() and micros() about ISR behaviour

### ISSUE THREAD

**Issue by mdcoding** [arduino/reference-en#572]
May it make sense to add a note to mills(), micros() and other concerned time functions about behavior inside an interrupt service routine like 'can call but will not count'.

**Comment by per1234** [comment]
Hi. Thanks for your suggestion.

The issues with `millis()`, `micros()`, and `delay()` are already documented in the `attachInterrupt()` reference page:
https://www.arduino.cc/reference/en/language/functions/external-interrupts/attachinterrupt/
Any suggestions for improvement on that documentation are welcome.
