### ISSUE TITLE
pulseIn improvement

### ISSUE THREAD

**Issue by woodlist** [arduino/reference-en#573]
As it is well documented here [https://www.arduino.cc/reference/en/language/functions/advanced-io/pulsein/](url) pulseIn returns microseconds. Having in mind too wide range of microcontrollers, when some of them have greather then 200Mhz internal clock frequency, while others do as low, as 8 MHz, the pulseIn is preferable to be able measure float values of microseconds, giving an opportunity to deal with incomming frequncy, up to 1MHz.

**Comment by per1234** [comment]
This repository is where we work on the content of the [Language Reference](https://www.arduino.cc/reference/en/) documentation. If you want to propose a change to `pulseIn`, you would need to do that here:
https://github.com/arduino/Arduino
