### ISSUE TITLE
Add link to documentation to repository.

### ISSUE THREAD

**Issue by SeppPenner** [arduino/reference-en#578]
In the other repositories, there is the link to the documentation in the github project heading (See image):

![image](https://user-images.githubusercontent.com/9639361/55629198-e3d9ae80-57b2-11e9-82f1-a9346fc69e5c.png)

I would suggest to add the link https://github.com/arduino/reference-en to the english repository, too.

@smellai @mastrolinux @robsoncouto (Whoever can do this).

**Comment by gvarisco** [comment]
Added in https://github.com/arduino/reference-en, thanks @SeppPenner for the heads up!
