### ISSUE TITLE
Incomplete documentation of PWM frequencies in analogWrite() reference

### ISSUE THREAD

**Issue by per1234** [arduino/reference-en#587]
Of PWM frequencies, the `analogWrite()` reference page says only:
>The frequency of the PWM signal on most pins is approximately 490 Hz. On the Uno and similar boards, pins 5 and 6 have a frequency of approximately 980 Hz.

This statement is not correct for all boards.

Originally reported at: https://github.com/arduino/Arduino/issues/8818

**Comment by animeshsrivastava24** [comment]
@per1234  Also, if we want we can cite a reference to analogWriteResolution of
[Arduino MKR](https://github.com/arduino/reference-en/blob/master/Language/Functions/Zero%2C%20Due%2C%20MKR%20Family/analogWriteResolution.adoc)
