### ISSUE TITLE
Is the syntax for `Stream.parseInt()` correct?

### ISSUE THREAD

**Issue by SeppPenner** [arduino/reference-en#588]
![grafik](https://user-images.githubusercontent.com/9639361/56869667-9ba15b00-6a03-11e9-9681-ff27aa6f202a.png)

https://www.arduino.cc/reference/en/language/functions/communication/stream/streamparseint/

I do not get the syntax there? What do the `'` do there??

**Comment by SeppPenner** [comment]
@robsoncouto Thank you for the merge, I was not completely sure if this was a syntax error or not.

**Comment by per1234** [comment]
Not only was the markup and formatting of the syntax section wrong, the information in the syntax section was also completely wrong. Investigating and correcting that issue lead me to find the same false information on three other pages. Thanks for bringing this to my attention @SeppPenner!

**Comment by SeppPenner** [comment]
@per1234 Oh, I didn't see that. But glad to know 👍
