### ISSUE TITLE
ABS() documentation is incorrect

### ISSUE THREAD

**Issue by thearduinoguy** [arduino/reference-en#597]
https://www.arduino.cc/reference/en/language/functions/math/abs/

Page states:

Returns
x: if x is greater than or equal to 0.
-x: if x is less than 0.

This is incorrect. If x is less than zero it will return the positive value of X. The page seems to imply that ABS has no affect on any integer.

**Comment by per1234** [comment]
Please see https://github.com/arduino/Arduino/issues/3338#issuecomment-115157321 for an explanation of why the documentation is correct.
