### ISSUE TITLE
Missing Characters subcategory in functions

### ISSUE THREAD

**Issue by smellai** [arduino/reference-en#60]

**Comment by SimonePDA** [comment]
Characters require a subfolder and I don't know (yet) how to do it properly through pull requests.
Pardon me, but I always used Edit and I am not fluent with Git.
For Characters I sent to Luca a ZIP file with the Ascii-Doc pages of the whole subcategory on July 14th.

**Comment by smellai** [comment]
Thanks, I'll add them
