### ISSUE TITLE
I want translate https://www.arduino.cc/reference/en/ into Polish.

### ISSUE THREAD

**Issue by tomb0x** [arduino/reference-en#600]
I want translate https://www.arduino.cc/reference/en/ into Polish language. I am one of the translators in the Arduino 1.5 IDE transifex team.

**Comment by per1234** [comment]
@gvarisco please create https://github.com/arduino/reference-pl and give me write access to it. Thanks!

**Comment by tomb0x** [comment]
How do I create a reference-en in arduino but not in tomb0x?   I created  github.com github.com  and what next?   I&#39;m new to github ... please help. Greetings.  
            
          
     
      
       
        Dnia 24 maja 2019 23:00 per1234 &lt;notifications@github.com&gt; napisał(a):
       
    
       
         github.com @gvarisco  please create  github.com github.com  and give me write access to it. Thanks!

**Comment by per1234** [comment]
Hi @tomb0x thanks so much for your interest in helping with the Arduino Language Reference translation project!

We create a dedicated repository for each translation language as volunteers step forward and offer their assistance in translating. We didn't already have a repository for the Polish language translation so we need to create one. It will be at https://github.com/arduino/reference-pl. After that, I'll copy over the English language content files from this repository. Each of those files will need to be translated to Polish. As soon as we have the repository set up, I'll let you know and provide any assistance you might need.

If you want to get started translating right away, you can go ahead and do so on your own repository or computer and then just copy those files over to the reference-pl repository once it's created.

**Comment by gvarisco** [comment]
> @gvarisco please create https://github.com/arduino/reference-pl and give me write access to it. Thanks!

done!

**Comment by SeppPenner** [comment]
Hi @per1234. What's the status? Any issues with https://github.com/arduino/reference-pl/pull/1?

**Comment by per1234** [comment]
@SeppPenner there are no issues with https://github.com/arduino/reference-pl/pull/1. It's only waiting for one of my colleagues from Arduino to merge it. Once that's done, the translation work can proceed.

**Comment by gvarisco** [comment]
Done, sorry for the delay!
