### ISSUE TITLE
Translation of Arduino Reference to the Hindi Language

### ISSUE THREAD

**Issue by animeshsrivastava24** [arduino/reference-en#617]
Please create a repository for translation to the Hindi Language. (Ref-hin)
Also, I have translated the Readme.md of the English Version to the Hindi Version.
Please have a view https://github.com/animeshsrivastava24/Arduino-Reference-to-Hindi/blob/master/README.md

**Comment by per1234** [comment]
@animeshsrivastava24 do you want this repository created for a Season of Docs project, or is it for volunteer work uninvolved with the Season of Docs program?

**Comment by animeshsrivastava24** [comment]
@per1234  Thank you so much for the response. I'll love to contribute as a volunteer for the work.

**Comment by per1234** [comment]
@gvarisco please create the https://github.com/arduino/reference-hi repository and give me write permissions in it. Thanks!

**Comment by gvarisco** [comment]
Done, https://github.com/arduino/reference-hi has been created.

**Comment by per1234** [comment]
Thanks @gvarisco!

@animeshsrivastava24 the reference-hi repository is now populated with the English Language Reference content awaiting translation to Hindi.
