### ISSUE TITLE
Arduino Micro Serial Pins

### ISSUE THREAD

**Issue by Obrekr** [arduino/reference-en#641]
The description of available serial ports on the Arduino Micro board on [Reference>Serial](https://www.arduino.cc/reference/en/language/functions/communication/serial/) is wrong.
Pins 0(RX) & 1(TX) are accessible by 'Serial1' not by 'Serial'.

I used 'Serial1' (instead of 'Serial') to talk to an external display controller (connected to pins 0 & 1) with Arduino IDE 1.8.9 and it started working.

**Comment by per1234** [comment]
Thanks for reporting this @Obrekr! I have submitted a pull request to correct the documentation: https://github.com/arduino/reference-en/pull/642
