### ISSUE TITLE
Double quotes in examples cannot be compiled 

### ISSUE THREAD

**Issue by leonty** [arduino/reference-en#699]
Sometimes in the examples I see characters that cannot really be used in a sketch. For example the non-symmetric double quotes:

> You can pass flash-memory based strings to Serial.print() by wrapping them with F(). For example:
> Serial.print(F(“Hello World”))

That just gives a compilation error if copied into the sketch:
> sketch_sep03a:8:1: error: stray '\342' in program
>  Serial.print(“Hello World”);
>  ^
> sketch_sep03a:8:1: error: stray '\200' in program
> sketch_sep03a:8:1: error: stray '\234' in program
> sketch_sep03a:8:1: error: stray '\342' in program
> sketch_sep03a:8:1: error: stray '\200' in program
> sketch_sep03a:8:1: error: stray '\235' in program
> /Users/leonty/Documents/Arduino/sketch_sep03a/sketch_sep03a.ino: In function 'void loop()':
> sketch_sep03a:8:17: error: 'Hello' was not declared in this scope
>  Serial.print(“Hello World”);
>                  ^
> exit status 1
> stray '\342' in program

I propose to replace them by normal programming double quotes "".

**Comment by SeppPenner** [comment]
This should be fixed with https://github.com/arduino/reference-en/pull/700.
