### ISSUE TITLE
Proposed digitalRead INPUT_PULLUP addition

### ISSUE THREAD

**Issue by snout** [arduino/reference-en#721]
For people new to using the Arduino IDE with various hardware, it might be worth pointing out that while a pullup is needed, and the Atmega328 has internal pullups when configured with INPUT_PULLUP, the compiler does not warn if the target (like an ESP32) doesn't have these internal pullups. So it's always wise to add this pullup resistor manually, if unsure.

**Comment by per1234** [comment]
We don't provide documentation specific to 3rd party boards. That is the responsibility of the 3rd party board package author. If Arduino was to ever make a board that didn't have support for `INPUT_PULLUP`, we should definitely document that.
