### ISSUE TITLE
Improving Documentation in Bits and Bytes section of the reference

### ISSUE THREAD

**Issue by ashpande** [arduino/reference-en#748]
Hello,

My GSoC project involves closely working with the language reference, and some sections are 'under documented' with not enough code examples and links in the 'see also' section. I will be submitting a few suggestions and making pull requests for those here.

**Comment by AshutoshPandey123456** [comment]
Added PR's 
https://github.com/arduino/reference-en/pull/749

https://github.com/arduino/reference-en/pull/750

https://github.com/arduino/reference-en/pull/751
