### ISSUE TITLE
doc for trim() function does not define whitespace

### ISSUE THREAD

**Issue by DaleSchultz** [arduino/reference-en#780]
I think **whitespace** should be added to the glossary (or elsewhere) and define what exactly is regarded as whitespace and then link to that from the trim() function reference at https://www.arduino.cc/reference/en/language/variables/data-types/string/functions/trim/

**Comment by cattledogGH** [comment]
The **whitespace** definition is here 
[https://docs.arduino.cc/built-in-examples/strings/StringLengthTrim](url)

Adding this link or the information to [ trim()](url) would be veruy helpful.

**Comment by per1234** [comment]
Hi @DaleSchultz. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/reference-en/issues/707.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
