### ISSUE TITLE
I've loaded the library file for Ridkey.h, but it still gets an error.

### ISSUE THREAD

**Issue by 1399568389** [arduino/reference-en#802]
I've loaded the library file for Ridkey.h, but it still gets an error.

The error message:
exit status 1
No 'keyboard' found.Does the project include '#include &lt;Keyboard.h&gt;'?

Short code:
#include <Keyboard.h>

void setup() {
  // make pin 2 an input and turn on the
  // pullup resistor so it goes high unless
  // connected to ground:
  pinMode(2, INPUT_PULLUP);
  Keyboard.begin();
}

void loop() {
  //if the button is pressed
  if (digitalRead(2) == LOW) {
    //Send the message
    keyboard.press("Hello!");
  }
}

**Comment by per1234** [comment]
This issue tracker is only to be used to report errors or make feature requests for the [Arduino Language Reference](https://www.arduino.cc/reference/en/). It is **NOT** a place to request assistance with your project. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
