### ISSUE TITLE
Misleading example in "array" reference page

### ISSUE THREAD

**Issue by PrismSync** [arduino/reference-en#813]
On the reference page for the datatype "array", an example of initialization was shown as the following:

notice that in line 3, the array was declared to be of 6 elements, yet only 5 elements are present in the { }initialization part. We understand that in reality the last element will be initialized as zero by default, but with the context, I'm afraid this might be understood as that the declared size number of an array should be 1 more than the number of elements (as that for char array)

[reference page for array](https://www.arduino.cc/reference/en/language/variables/data-types/array/
)
![image](https://user-images.githubusercontent.com/62847781/106311657-74df1b00-62a0-11eb-9b3c-4620757ff824.png)

**Comment by mohammedhemed77** [comment]
Oh, you are correct , I agree with you.
