### ISSUE TITLE
Missing documentation digitalPinToInterrupt

### ISSUE THREAD

**Issue by sterretjeToo** [arduino/reference-en#825]
Can't find the documentation (reference page) for digitalPinToInterrupt. It's not on https://www.arduino.cc/reference/en/ and it's not on any of the interrupt related pages like https://www.arduino.cc/reference/en/language/functions/external-interrupts/attachinterrupt/ (although it is used there and explained); would have expected a link on attachInterrupt page and detachInterrupt page.

**Comment by karlsoderby** [comment]
Hi @sterretjeToo , thanks for the suggestion, I just added this to the reference. 

Here is the PR: https://github.com/arduino/reference-en/pull/938
