### ISSUE TITLE
Redundancy in Reference > Variables > Constants > Defining Pin Levels > HIGH

### ISSUE THREAD

**Issue by That-Guy977** [arduino/reference-en#839]
Redundant "Volts" in the Constants Reference Page (Defining Pin Levels > High)

>When a pin is configured as an INPUT with pinMode(), and read with digitalRead(), the Arduino (ATmega) will report HIGH if:
>
>• a voltage greater than 3.0V is present at the pin (5V boards)
>
>• a voltage greater than 2.0V **_volts_** is present at the pin (3.3V boards)

https://www.arduino.cc/reference/en/language/variables/constants/constants/

**Comment by per1234** [comment]
Fixed by https://github.com/arduino/reference-en/pull/840. Thanks @That-Guy977!

**Comment by That-Guy977** [comment]
thanks @per1234
