### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dsyleixa** [arduino/reference-en#856]
String method readStringUntil() is not documented in reference:
https://www.arduino.cc/reference/en/language/variables/data-types/stringobject/

**Comment by per1234** [comment]
It is a method of the `Stream` class, not of the `String` class. So it is documented in the `Stream` reference:
https://www.arduino.cc/reference/en/language/functions/communication/stream/streamreadstringuntil/

**Comment by dsyleixa** [comment]
yes, I just noticed that by myself (cross-over posted/edited).
Nonetheless I would appreciate to have that additionally to substr() or whatever:

String s, str ="123456789abc";;
s=str.readStringUntil('a');
Serial.println(s);
