### ISSUE TITLE
Question: Understanding what this documentation affects

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [arduino/reference-en#9]
Hi, I am new to project collaboration, and periodically have modifications/additions I'd like to make to the Arduino documentation, but I never knew how to do so. 

**I want to know: if I fork, modify, and do a pull request on this documentation repository, what documentation does it affect?**
ie:
1) Arduino Website Documentation? (http://arduino.cc/en/Reference/HomePage)
2) Local IDE documentation on future downloads? (accessed via IDE help menu)
3) anywhere else I should know?

Thanks. I would like to make contributions to Arduino where able, and I think I finally have a decent idea how to do so. 

**Side Question**: anyone know what the process is for getting a new library included as part of the Arduino core?

**Comment by mastrolinux** [comment]
Hi,

This repo is for the following purpose in reply to your questions.
1) yes it will be there but will be deployed on April/May this year
2) same thing
3) maybe there will be a new Wed IDE containing the last version of this repo and/or a printable version of this repo on the website
