### ISSUE TITLE
Round() is mentioned in the Float ref page but neither have a ref page, nor is listed in the top Language Ref page

### ISSUE THREAD

**Issue by RaphTronic** [arduino/reference-en#989]
The ref page for float (Reference>Language>Variables>Data types>Float) mentions:

_or use the **round()** function:
float x = 2.9;
int y = **round(x)**_

But round() is not hyperlinked and is NOT listed in the top Language Reference list: www.arduino.cc/reference/en/

So users can't find out how round() works: round(2.01)=???, round(2.49)=???, round(2.5)=???, round(2.51)=???

**Comment by per1234** [comment]
Hi @RaphTronic. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/reference-en/issues/927.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
