### ISSUE TITLE
documentation joinOTAA() missing return values information

### ISSUE THREAD

**Issue by mac-arno** [arduino/reference-en#997]
[Reference] >[ Libraries] >[ Mkrwan] > Joinotaa
In the documentation for the function joinOTAA() there is an information missing regarding the expected return values. What integer is returned on successfull connection? Which integers for unsuccessful connection?

**Comment by per1234** [comment]
Hi @mac-arno. The documentation for the MKRWAN library is not hosted in this repository. The documentation is hosted in the library repository:

https://github.com/arduino-libraries/MKRWAN/tree/master/docs

So I will close the issue as off topic for this repository. I believe you have already reported the deficiency in the appropriate issue tracker: https://github.com/arduino-libraries/MKRWAN/issues/139
